### ISSUE TITLE
Changing a stack should be possible using previous parameter values.

### ISSUE THREAD

**Issue by muja** [theserverlessway/formica#86]
When updating a stack, most of the parameters do not change and it can often be cumbersome to pass in all the same parameters that the previous stack uses, especially if it was randomly generated (e.g. a generated password for a DB instance).

The `aws-cli` provides a `UsePreviousValue` option: something similar would definitely be useful. The straight forward way would probably be to have a flag `--reuse-parameters <Parameter1>,<Parameter2>,<Parameter3>...`.

Thoughts?

**Comment by flomotlik** [comment]
Yeah especially for passwords you only want to send in once but then keep around and not write to a config file this would be very helpful.

In general I mostly use config files to store parameters which makes it easy to pass the same ones in all the time, but for this case something else would be neat.

First thought is to make this a config file only option as it would be easier to implement and more understandable for those edge cases. I don't think I want to add another flag because that could lead to confusion when you set a value on the parameter, but then tell it to reuse the same parameter.

But I do like the feature. I'll probably not get around to it for a while, but happy to work on it if someone wants to pick it up.

**Comment by muja** [comment]
In general, I'm not the biggest fan of the config file, I don't use them myself. Especially since 99% of the time, I will need to write a wrapper script anyway, it's more convenient to deploy an entire stack via the command line. Correct me if I'm wrong, but currently the config is completely optional as all features are available via the CLI, so this would introduce an inevitable need for a config file just for this option.

**Comment by flomotlik** [comment]
Not all features are available on the cli, e.g. nested vars can only be set in config files (this should be the only one at the moment). I'm typically creating config files for different environments (dev.config.yaml, staging.config.yaml) and then for shared options create a common.config.yaml. Formica allows you to load multiple config files and for them to override values, e.g. `formica new -c common.config.yaml dev.config.yaml`

I want the cli options to be for most common use cases, but I'm generally fine with moving some options that need more complex or nested config to config files. One thing I could think of here would be the following config file:

```
stack: somestack
parameters:
  SomeParameter:
    reuse: true
```

> In general, I'm not the biggest fan of the config file, I don't use them myself. Especially since 99% of the time, I will need to write a wrapper script anyway, it's more convenient to deploy an entire stack via the command line

Would be interesting to know why you don't like the config files or need to write wrapper scripts. Really intending formica to be used by developers directly (or in some Makefile probably).

**Comment by muja** [comment]
> Would be interesting to know why you don't like the config files or need to write wrapper scripts. Really intending formica to be used by developers directly (or in some Makefile probably).

Most of the time, I need to lookup some ARN of some resource (e.g. certificate) and pass it as parameter. For this use case, however, I'm beginning to think it's more idiomatic to export reusable resources in a different stack so I can `!ImportValue` them.

Or for the "reuse", I do it "manually" with

    aws cloudformation describe-stacks --output text \
      --stack-name $STACK_NAME \
      --query 'Stacks[0].Parameters[?ParameterKey==`VariableToReuse`].ParameterValue'

Also, the lack of an `upsert` command currently forces me to `formica (change|new)` variably. For the `new` command, I also automatically remove the stack on failure.

And since I have to do all these anyway, I don't see the value of having a config file in my repository. I might as well pass the few parameters via the command line.

**Comment by flomotlik** [comment]
>For this use case, however, I'm beginning to think it's more idiomatic to export reusable resources in a different stack so I can !ImportValue them.

As long as they are in the same region then yes definitely export/import. There is one usecase when you want to use a certificate for a CloudFront distribution where the cert has to be in us-east-1 no matter where you create the CF distribution. For those cases I really think the config file (especially one for each environment) is a good tradeoff. You can store them in your repo and make it easy for anyone to come in and deploy.

>And since I have to do all these anyway, I don't see the value of having a config file in my repository. I might as well pass the few parameters via the command line.

Most importantly here imho is that it documents the parameters and makes the config file usable by someone else on the team. CLI is great for quick things or when working on it only yourself, but it imho creates a situation where you could either have a typo and deploy something you don't want or somebody else doesn't know how to deploy a stack correctly.

Thats where upsert also becomes dangerous because a typo in a Parameter could mean an unstoppable change happening. With change/deploy you at least always have a step in between.

**Comment by flomotlik** [comment]
There is now (for a while) an option to use previous parameters, so I'm closing this. Thanks for reporting!
